### PR TITLE
Welcome Feature

### PR DESCRIPTION
**Pull request by Sneagan**
I want to know if you're interested in this before I spend any more time generalizing it. It uses the poll behavior to check participants in a given room, as well as on the server and send them a welcome message via a direct message room. It needs some minor work to make its behavior conditional for users who don't want it on.

### CODE REVIEW

**Comment by vranki** [comment]
The feature looks good, but I'd like to request few changes:

 - Allow admin to set the configuration with matrix commands instead of setting environment variables. Hemppa is designed to have minimal configuration and all settings should be manageable with bot commands. See how other modules handle it and store settings in account data of the bot user.
 - Add documentation of the module to readme.md
 - Set the module disabled by default (self.enabled = False , see cmd.py for example)

**Comment by Sneagan** [comment]
Great feedback. I'll sort this out and submit an update in the next couple of days.

**Comment by Sneagan** [comment]
@vranki I believe that I've made the requested changes. Let me know if I've missed something.

**Comment by Sneagan** [comment]
@vranki I think it's ready for another look. At your leisure. :)

**Review by vranki — APPROVED** [review]
LGTM, thanks for contributing!

**Pull request merged**
