### PR TITLE
Adding giphy, gfycat and Tautulli bot, splitted handling for image upload and send

### PR DESCRIPTION
**Pull request by aspacca**
I've developed these bots for myself, please let me know if you'd like to add to the main repo

### CODE REVIEW

**Comment by vranki** [comment]
Thanks, these look like good modules and changes. Please also update README.md and document them. Also document how to upload an image from module in the "Module API" section.

**Comment by aspacca** [comment]
> Please also update README.md and document them. Also document how to upload an image from module in the "Module API" section.

I will do in the next days

**Comment by aspacca** [comment]
Tautulli bot could be a little troubelsome: since I didn't want to port the whole image generation logic from Tautulli code to hemppa I initialize Tautulli inside the bot using it's current setup. The problem is that I have to add the import path for the installed version of Tautulli, and if it's not installed/env variable setup, hemppa will fail.
Do you have any hint?
Python is not my principal language and I'm not sure if I could wrap the import part in a `try/except`

**Comment by vranki** [comment]
Maybe try to load it like modules and catch the error? See https://github.com/vranki/hemppa/blob/master/bot.py#L310

**Review by vranki — CHANGES_REQUESTED** [review]
LGTM, but add documentation to README.md - also for the shared image upload functions.

**Comment by aspacca** [comment]
documentation added

**Comment by vranki** [comment]
Documentation looks good, thanks. But one more change request: Please don't use any env variables for API keys etc. Create a command to set the API key (usable for bot owner only) and store it in the module settings. See other modules to see how it's done. 

Reason is that env variables must all be registered in the Dockerfile so I would not want to have module specific ones in there.

**Comment by aspacca** [comment]
@vranki sure. I see that apod module accepts both command setup and env variable for api key, while teamup only the command: I should use the later, is it?

what about the remaining env variables? those are needed upon module bootstrap

**Comment by vranki** [comment]
Yes, prefer a setting command where possible. If not possible, I suppose env variable is fine. Just document that it needs to be added to Docker files if running in docker environment.

**Comment by aspacca** [comment]
done

**Comment by vranki** [comment]
Merged, thanks. Let's do further fixes in new PR's.

**Pull request merged**
