### PR TITLE
Only talk to external services when enabled explicitly

### PR DESCRIPTION
**Pull request by berlincount**
... mostly had to disable the sideeffect-heavy twitterscraper import while working on something else.

Couldn't test (yet) whether it still works or needs some other fixes.

### CODE REVIEW

**Comment by vranki** [comment]
LGTM otherwise, but please update README.md with the modules that are disabled by default. I'm also tempted to just remove twitter module as the scraper doesn't work reliably.

**Comment by berlincount** [comment]
I can do that in another commit in this PR, if you want

**Comment by vranki** [comment]
Yes, you can update this PR. Can you also test it first and let me know before I merge it?

**Comment by berlincount** [comment]
Nah, I meant removing Twitter - I don't have time to test that **peep**, and I'm not surprised it doesn't work reliable - it uses some random Free Proxy List service and does all kind of bogus queries to the outside world I don't want to debug, tbh.

**Comment by vranki** [comment]
Agreed, the scraped lib is horrible.. I wonder if there are better alternatives. At least I didn't find any that worked last time I tried. The twitter functionality would be nice to have though..

**Comment by davralin** [comment]
> I wonder if there are better alternatives

Check #105 - there are some alternatives mentioned there.

**Pull request merged**
